//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_familiar
    {
        public string usuario { get; set; }
        public string cedula { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string genero { get; set; }
        public string parentesco { get; set; }
        public decimal edad { get; set; }
        public string menor_edad { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public System.DateTime fecsys { get; set; }
    }
}
